executor: slurm
jobs: 10
default-resources:
  slurm_partition: "sapphire"
  mem_mb: 900000
  runtime: 1440

latency-wait: 60
use-conda: false
printshellcmds: true
keep-going: true
rerun-incomplete: true
