executor: slurm
jobs: 14
default-resources:
  slurm_partition: "sapphire"
  slurm_account: "cga"  # Optional, usually inferred or defaults
latency-wait: 60
use-conda: false
printshellcmds: true
keep-going: true
rerun-incomplete: true